name: Every Push On Client
run-name: ${{ github.actor }} is testing out on pushed commits 🚀
on:
  push:
    branches:
      - client
      - client-**
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
