name: Every Push On Client
run-name: ${{ github.actor }} is testing out on pushed commits 🚀
on:
  push:
    branches:
      - client
      - client-**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - with:
        - working-directory: client
        - run: npm install
        - run: npm run build
