name: Every Push On Client

on:
  push:
    branches: [ client ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
