name: Every Push On Server
run-name: ${{ github.actor }} is testing out on pushed commits 🚀
on:
  push:
    branches:
      - server
      - server-**
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect repository
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: real-todolist
          yaml: |-
            name: real-todolist
            app: node@16
            options:
              git:
                ref: ${{ github.ref }}
                url: git@github.com:${{ github.repository }}.git
