name: Every Push On Server
run-name: ${{ github.actor }} is testing out on pushed commits 🚀
on:
  push:
    branches:
      - server
      - server-**
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "real-todolist"
          heroku_email: "sinwonse@gmail.com"
